### PR TITLE
ClusterIPAddress: New Resource to add IP Addresses to clusters

### LINKED ISSUE #151: ClusterIPAddress: New Resource
**Details of the scenario you tried and the problem that is occurring:**
Add the ability to manipulate Cluster IP Addresses. This will allow the addition of multiple cluster IP resources for the cluster as well as manipulating the "Name" metadata property.  Cluster IP addresses are identified by IP Address & Network Mask combination.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System and PowerShell the DSC Target Node is running:**
This should be compatible with all versions

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
dev

### PR DESCRIPTION
**Pull request by nickgw**
#### Pull Request (PR) description

`ClusterIPAddress`
- New resource to add IP Addresses to Clusters if the ClusterNetwork exists in the Cluster.
- This needs to be separate from `Cluster` because creating the object will fail until the `ClusterNetwork` has been added either via `DSC_ClusterNetwork` or a node in that network joins the cluster.

#### This Pull Request (PR) fixes the following issues

- Fixes #151 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
I just quickly browsed through the code. I have to do a bit of a deeper dive another day. But a few comments at least.

> Reviewed 55 of 60 files at r5, 1 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-:-N48yB7j9FZDO9mwT6XZ:bgpgb2e)* status: 56 of 60 files reviewed, 12 unresolved discussions (waiting on @johlju and @nickgw)

*[a discussion](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-N48sa9E9fJIYQss_2sa:-N48sa9E9fJIYQss_2sb:b5s795s) (no related file):*
I'm curious, can this potentially remove the IP address that is added by the resource ClusterNetwork if a configuration is passing `'Absent'` for the same IP address with this new resource?

___
___
*[`CHANGELOG.md` line 15 at r6](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-N48wmkpEvPLDSA4GsNO:-N48wmkpEvPLDSA4GsNP:b3qkcbk) ([raw file](https://github.com/dsccommunity/failoverclusterdsc/blob/a51be255714a2e2535bb37772749e4a239329609/CHANGELOG.md#L15)):*
> ```Markdown
> ### Changed
> - BREAKING CHANGE
>   - Renamed _xFailOverCluster_ to _FailoverClusterDsc_ - fixes [Issue #69](https://github.com/PowerShell/xFailOverCluster/issues/69).
> ```

This should not be in this section, seems to be duplicate from further down.



_Code quote:_
```Markdown
### Changed
- BREAKING CHANGE
  - Renamed _xFailOverCluster_ to _FailoverClusterDsc_ - fixes [Issue #69](https://github.com/PowerShell/xFailOverCluster/issues/69).
  - Changed all MSFT_xResourceName to DSC_ResourceName.
  - Updated DSCResources, Examples, Modules and Tests for new naming.
  - Updated README.md from _xFailOverCluster_ to _FailoverClusterDsc_
```
___
*[`source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1` line 6 at r6](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-N48tQWP98VqotZ2X5mL:-N48tQWP98VqotZ2X5mM:bjuq4m5) ([raw file](https://github.com/dsccommunity/failoverclusterdsc/blob/a51be255714a2e2535bb37772749e4a239329609/source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1#L6)):*
> ```PowerShell
> 
> $script:localizedData = Get-LocalizedData -DefaultUICulture 'en-US'
> function Get-TargetResource
> ```

We should add comment-based help to the Get-, Set-, and Test-function.



_Code quote:_
```PowerShell
unction Get-TargetResource
```
___
*[`source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1` line 22 at r6](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-N48rIdF5UD00VabWxU5:-N48rIdF5UD00VabWxU6:b4l7us6) ([raw file](https://github.com/dsccommunity/failoverclusterdsc/blob/a51be255714a2e2535bb37772749e4a239329609/source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1#L22)):*
> ```PowerShell
>         [Parameter()]
>         [System.String]
>         [ValidateSet('Present', 'Absent')]
> ```

We should not need this non-mandatory parameter in the Get-function. Se next comment.



_Code quote:_
```PowerShell
        [Parameter()]
        [System.String]
        [ValidateSet('Present', 'Absent')]
        $Ensure = 'Present'
```
___
*[`source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1` line 32 at r6](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-N48r6QB6AwG3twZY_Y8:-N48r6QB6AwG3twZY_Y9:b-qkf62w) ([raw file](https://github.com/dsccommunity/failoverclusterdsc/blob/a51be255714a2e2535bb37772749e4a239329609/source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1#L32)):*
> ```PowerShell
>         IPAddress   = $null
>         AddressMask = $null
>         Ensure      = $Ensure
> ```

This should be set to 'Absent' if the IP address does not exist and 'Present' if the IP address do exist.



_Code quote:_
```PowerShell
Ensure      = $Ensure
```
___
*[`source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1` line 41 at r6](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-N48xdDl10To0f7KAXKC:-N48xdDl10To0f7KAXKD:b-cdbqp9) ([raw file](https://github.com/dsccommunity/failoverclusterdsc/blob/a51be255714a2e2535bb37772749e4a239329609/source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1#L41)):*
> ```PowerShell
>         $ipResourceDetails = Get-ClusterIPResourceParameters -IPAddressResourceName $ipResource.name
> 
>         if ( $ipResourceDetails.Address -eq $IPAddress )
> ```

Since netmask is mandatory parameter should it not also look that the netmask is correct. But maybe there is not possible to add the same IP adress with multiple netmasks, so maybe thatis why it only checks for IP address? :thinking: 



_Code quote:_
```PowerShell
f ( $ipResourceDetails.Address -eq $IPAddress )
```
___
*[`source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1` line 131 at r6](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-N48tmip3BVx3nuJuCdY:-N48tmip3BVx3nuJuCdZ:b-2eovha) ([raw file](https://github.com/dsccommunity/failoverclusterdsc/blob/a51be255714a2e2535bb37772749e4a239329609/source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1#L131)):*
> ```PowerShell
>     # # If IPAddress is not in ClusterResource DependencyExpression #fail
>     # # If IPAddress' Subnet is not in ClusterNetworks #fail
>     # $testResult = Test-ClusterIPAddressDependency -IPAddress $IPAddress
> ```

Should this be removed?



_Code quote:_
```PowerShell
    # # If IPAddress is not in ClusterResource DependencyExpression #fail
    # # If IPAddress' Subnet is not in ClusterNetworks #fail
    # $testResult = Test-ClusterIPAddressDependency -IPAddress $IPAddress
    # $testTargetResourceReturnValue = $false
```
___
*[`source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1` line 318 at r6](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-N48uGQt1l-efbGe4Mg7:-N48uGQt1l-efbGe4Mg8:b735m7v) ([raw file](https://github.com/dsccommunity/failoverclusterdsc/blob/a51be255714a2e2535bb37772749e4a239329609/source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1#L318)):*
> ```PowerShell
>         Test-ClusterIPAddressDependency -IPAddress 10.235.0.141 -verbose
> #>
> function Test-ClusterIPAddressDependency
> ```

This function seem never to be called?



_Code quote:_
```PowerShell
Test-ClusterIPAddressDependency
```
___
*[`source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1` line 427 at r6](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-N48ulpn8nYX1SUvZ-ov:-N48ulpn8nYX1SUvZ-ow:b9dqgkv) ([raw file](https://github.com/dsccommunity/failoverclusterdsc/blob/a51be255714a2e2535bb37772749e4a239329609/source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1#L427)):*
> ```PowerShell
>         Returns the cluster Dependency expression for a given cluster.
> #>
> function Get-ClusterResourceDependencyExpression
> ```

If the function at the previous comment above is removed, then this function seem never to be called?



_Code quote:_
```PowerShell
Get-ClusterResourceDependencyExpression
```
___
*[`source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1` line 517 at r6](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-N48v1Dt0VjEFHla-yqm:-N48v1Dt0VjEFHla-yqn:b735m7v) ([raw file](https://github.com/dsccommunity/failoverclusterdsc/blob/a51be255714a2e2535bb37772749e4a239329609/source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1#L517)):*
> ```PowerShell
>         OwnerGroup of the cluster to remove the IP resource from
> #>
> function Remove-ClusterIPResource
> ```

This function seem never to be called?



_Code quote:_
```PowerShell
Remove-ClusterIPResource
```
___
*[`source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1` line 675 at r6](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-N48vPfuCMnNWgqZu-Jz:-N48vPfuCMnNWgqZu-K-:bgob4u3) ([raw file](https://github.com/dsccommunity/failoverclusterdsc/blob/a51be255714a2e2535bb37772749e4a239329609/source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1#L675)):*
> ```PowerShell
>     )
> 
>     $ipObject = [System.Net.IPAddress]::Parse($IPAddress)
> ```

Instead of assigning to a variable that is then never used, can be output to null instead?



_Code quote:_
```PowerShell
$ipObject =
```
___
*[`source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1` line 730 at r6](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-N48vxB70eGBs-7jtxyc:-N48vxB70eGBs-7jtxyd:b-ydezlo) ([raw file](https://github.com/dsccommunity/failoverclusterdsc/blob/a51be255714a2e2535bb37772749e4a239329609/source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1#L730)):*
> ```PowerShell
> {
>     [CmdletBinding()]
>     [OutputType([System.String])]
> ```

Looks like this function does not return a string.



_Code quote:_
```PowerShell
[OutputType([System.String])]
```

**Comment by nickgw** [comment]
I think I've resolved everything in your comments. Just futzing with tests now. I think I'm having issues figuring out how to mock the foreach loop in `Get-ClusterIPResourceFromIPAddress`.

As for your two questions:

1. I'm curious, can this potentially remove the IP address that is added by the resource ClusterNetwork if a configuration is passing 'Absent' for the same IP address with this new resource?

Yes, it will remove that IP address, leaving the cluster in an offline state. I don't know why anyone would want to do that, and if you think it's the right path I can write some logic to throw when there is only one IP address and DSC is trying to remove it.

2. Since netmask is mandatory parameter should it not also look that the netmask is correct. But maybe there is not possible to add the same IP adress with multiple netmasks, so maybe thatis why it only checks for IP address? 🤔

I think generally, the IP address is what matters to be added. If you try and add an IP address that falls in the same address scope as an already added network, but with a different AddressMask, `Test-ClusterNetwork` will catch that in Set and throw. 

3. Instead of assigning to a variable that is then never used, can be output to null instead? (In `Test-IPAddress`) 

I'm assigning it a variable because otherwise the System.Net.IPAddress object is returned. The resource doesn't care about that information, just that the IP address `String` passed is able to be casted to an IPAddress object. 

I don't know best practices here, but I just tested quickly and `[System.Net.IPAddress]::Parse($IPAddress) | Out-Null` serves the same purpose as assigning a variable and never using it. Let me know what you think here.

**Comment by johlju** [comment]
> I think I'm having issues figuring out how to mock the foreach loop in `Get-ClusterIPResourceFromIPAddress`

Debugging the test it was that you wanted to return a hashtable, but the return statement was on one row and hashtable on the next line, so it just ran `return` and never returned the hashtable. 🙂 
But when debugging the tests I had to fix a few extra things, to they are in a PR here for you to merge if you like: https://github.com/nickgw/FailOverClusterDsc/pull/1

**Comment by johlju** [comment]
> Yes, it will remove that IP address, leaving the cluster in an offline state. I don't know why anyone would want to do that, and if you think it's the right path I can write some logic to throw when there is only one IP address and DSC is trying to remove it.

I think I misunderstood the purpose of ClusterNetwork - after digging in further it does not create anything new, just update an existing network. So my initial thought that these will collide in some way was not true. So no need to do anything. 🙂

**Comment by johlju** [comment]
> I think generally, the IP address is what matters to be added. If you try and add an IP address that falls in the same address scope as an already added network, but with a different AddressMask, `Test-ClusterNetwork` will catch that in Set and throw.

Sounds good, lets go with that.

**Comment by johlju** [comment]
> I don't know best practices here, but I just tested quickly and `[System.Net.IPAddress]::Parse($IPAddress) | Out-Null` serves the same purpose as assigning a variable and never using it. Let me know what you think here.

Using either `| Out-Null` or `$null = ...` will avoid getting the lint error "variable is assigned but never used". So rather se we either assign it or pipe it to null.

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270)* status: 55 of 60 files reviewed, 6 unresolved discussions (waiting on @johlju and @nickgw)

___
*[`source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1` line 22 at r6](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-N48rIdF5UD00VabWxU5:-N4HajmOEWGPQluJJv_T:bdkd3f2) ([raw file](https://github.com/dsccommunity/failoverclusterdsc/blob/a51be255714a2e2535bb37772749e4a239329609/source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1#L22)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should not need this non-mandatory parameter in the Get-function. Se next comment.
</blockquote></details>

We can remove the Ensure parameter. The Get-function should only contain non-mandatory parameter that are used in the code, since we no longer reference the parameter we can remove it here. (the Test- and Set- function must always have all properties in the schema, but no the Get function)
___
*[`source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1` line 66 at r8](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-N4HaCdEDwjXbxzMh7Mi:-N4HaCdEDwjXbxzMh7Mj:btpd1b0) ([raw file](https://github.com/dsccommunity/failoverclusterdsc/blob/de0207b58b284b39c8f4a2c143c8965685ee8a6f/source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1#L66)):*
> ```PowerShell
>         Sets the state of the failover cluster IP address.
> 
>     .PARAMETER IPAddress
> ```

Please also add for Ensure parameter for Set- and Test-function (Esnure should be removed from Get per previous comment, so should not be there). :slightly_smiling_face: 



_Code quote:_
```PowerShell
.PARAMETER
```

**Review by johlju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270)* status: 55 of 60 files reviewed, 7 unresolved discussions (waiting on @johlju and @nickgw)

___
*[`README.md` line 109 at r11](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-N4IeSan0AEooXy8OT3N:-N4IeSan0AEooXy8OT3O:b-iijdn8) ([raw file](https://github.com/dsccommunity/failoverclusterdsc/blob/ec3be6171c0f2d6f57787f32aef7d7b443866abc/README.md#L109)):*
> ```Markdown
> * [Remove a cluster disk from the failover cluster](/source/Examples/Resources/ClusterDisk/2-ClusterDisk_RemoveClusterDiskConfig.ps1)
> 
> ### ClusterIPAddress
> ```

@nickgw I merged a PR that removed the resource documentation (the section `## Resources`)  from README.md. The "wiki auto-doc" generates the resource descriptions from the schema MOF on build (and pushes on deploy). A quick glance I saw that the descriptions in schema differ (at least one of them) from the ones in the README.md. Keep the text you think is best descriptive. :slightly_smiling_face: 

Now we don't need to update in two places. :slightly_smiling_face:  



_Code quote:_
```Markdown
### ClusterIPAddress
```

**Comment by johlju** [comment]
@nickgw I won't have time to look over this tonight or tomorrow. So will look at it after a workday next week.

**Comment by nickgw** [comment]
@johlju no worries! I think I've updated everything, and am ready for hopefully your final review! I appreciate all the time you've spent on this.

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r7, 2 of 2 files at r11, 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270)* status: all files reviewed, 4 unresolved discussions (waiting on @nickgw)

___
*[`source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1` line 318 at r6](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-N48uGQt1l-efbGe4Mg7:-N4vlBjv64WpoTCUYXKW:bwt7vah) ([raw file](https://github.com/dsccommunity/failoverclusterdsc/blob/a51be255714a2e2535bb37772749e4a239329609/source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1#L318)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This function seem never to be called?
</blockquote></details>

Since this function is not used, can we remove it? 
___
*[`source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1` line 427 at r6](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-N48ulpn8nYX1SUvZ-ov:-N4vlflv2HN3um98CUX7:b-pym7h3) ([raw file](https://github.com/dsccommunity/failoverclusterdsc/blob/a51be255714a2e2535bb37772749e4a239329609/source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1#L427)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

If the function at the previous comment above is removed, then this function seem never to be called?
</blockquote></details>

Since this function is only used by a function that should be removed (se other comment), then this will not be used son cab can we remove it? 
___
*[`source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1` line 619 at r12](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-N4vmTL4EBAhEZPqMQbN:-N4vmTL4EBAhEZPqMQbO:bytpsa9) ([raw file](https://github.com/dsccommunity/failoverclusterdsc/blob/760c2681f26351b1fe566e2ca55af3710ed24ee6/source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1#L619)):*
> ```PowerShell
>         Address mask of the IP address
> #>
> function Remove-ClusterIPParameter
> ```

This function is not used, can we remove it?



_Code quote:_
```PowerShell
function Remove-ClusterIPParameter
```
___
*[`tests/Unit/DSC_ClusterIPAddress.Tests.ps1` line 1020 at r12](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-N4vnYZbB83EnjnBR9Ww:-N4vnYZbB83EnjnBR9Wx:bu6bll6) ([raw file](https://github.com/dsccommunity/failoverclusterdsc/blob/760c2681f26351b1fe566e2ca55af3710ed24ee6/tests/Unit/DSC_ClusterIPAddress.Tests.ps1#L1020)):*
> ```PowerShell
>                 Assert-MockCalled -CommandName Get-ClusterIPResource -Times 1
>                 Assert-MockCalled -CommandName Get-ClusterIPResourceParameters -Times 2
>                 #Assert-MockCalled -CommandName Get-ClusterResource -Times 0
> ```

We can remove this line if the assert should not be here.

**Review by nickgw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270)* status: 59 of 61 files reviewed, 4 unresolved discussions (waiting on @johlju and @nickgw)

___
*[`source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1` line 318 at r6](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-N48uGQt1l-efbGe4Mg7:-N4w6AVfE7XWjRUEs9LF:b-896fix) ([raw file](https://github.com/dsccommunity/failoverclusterdsc/blob/a51be255714a2e2535bb37772749e4a239329609/source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1#L318)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Since this function is not used, can we remove it? 
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1` line 427 at r6](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-N48ulpn8nYX1SUvZ-ov:-N4w7laoEMsF0Gz0TSjc:b-896fix) ([raw file](https://github.com/dsccommunity/failoverclusterdsc/blob/a51be255714a2e2535bb37772749e4a239329609/source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1#L427)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Since this function is only used by a function that should be removed (se other comment), then this will not be used son cab can we remove it? 
</blockquote></details>

Done.



_Code quote:_
```PowerShell
Get-ClusterResourceDependencyExpression
```
___
*[`source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1` line 619 at r12](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-N4vmTL4EBAhEZPqMQbN:-N4w7eMu6-foDCcsKJUR:b-896fix) ([raw file](https://github.com/dsccommunity/failoverclusterdsc/blob/760c2681f26351b1fe566e2ca55af3710ed24ee6/source/DSCResources/DSC_ClusterIPAddress/DSC_ClusterIPAddress.psm1#L619)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This function is not used, can we remove it?
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r13, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270#-:-N4wJeHH4uirOn765gpT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nickgw)

**Review by johlju — APPROVED** [review]
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/270)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nickgw)

**Pull request merged**
